<a href="https://colab.research.google.com/github/skyler-ud/FDSFE_SLindsey/blob/main/inclasscode/python_bootcamp_MLTSA25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
my_str='hello'


In [2]:
my_str

'hello'

In [4]:
print(my_str)

hello


In [5]:
my_int=36

In [6]:
my_float=36.

In [7]:
my_int*my_float

1296.0

In [8]:
my_int*my_str

'hellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohello'

In [9]:
import numpy as np

In [11]:
my_nparr=np.array([1,2,3])

In [12]:
my_nparr

array([1, 2, 3])

In [13]:
my_int*my_nparr

array([ 36,  72, 108])

In [14]:
my_bool=True

In [15]:
my_int==6

False

In [16]:
my_int==36

True

In [17]:
if my_int!=36:
  print('my_int is not 36')
else:
  print('my_int is 36')


my_int is 36


In [19]:
my_nparr.dtype

dtype('int64')

In [21]:
my_nparr.max()

3

In [22]:
my_nparr[2]

3

In [23]:
my_nparr[-1]

3

In [24]:
my_nparr[1:3]

array([2, 3])

In [25]:
list(range(1,4))

[1, 2, 3]

In [27]:
for a in range(1,4):
  print(sum(np.arange(0,a))) #np.arange() is the same as range() but returns a numpy array

0
1
3


In [28]:
a

3

In [46]:
def allodds(max):
  """
  This is called a docstring!

  Prints odd numbers
  Input:
    max: (int) last number in the list
  Return:
    a list of odd numbers from 0 to max
  """
  odds=[]
  for i in range(1,max+1):
    if a % 2 == 1:
      odds.append(a)
      #print(odds)
  return odds


In [47]:
allodds?
#This prints the name of the function, the inputs, and the docstring (if there is one)

SyntaxError: invalid syntax (<ipython-input-47-323d96023473>, line 1)

In [48]:
print(allodds(10)) #why is this just appending 3 a bunch of times???

[3, 3, 3, 3, 3, 3, 3, 3, 3, 3]


In [75]:
word='tacocat'
def Palindrome_Checker(Input):
  Result=1
  if isinstance(Input,str):
    print('Input is a string')
    if Input.lower() == Input[::-1].lower():
      Result==2
    else:
      Result==3
  return Result

In [76]:
Palindrome_Checker(word)

Input is a string


1

In [71]:
word[::-1]

'tset'